sudo: required
dist: bionic
matrix:
  fast_finish: true
  include:
      - env: CLANG_VERSION=8
        compiler: clang-8
        addons:
          apt:
            packages:
              - clang-8
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-xenial-8
language: c
before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
install:
  - source travis-utils/emsg.sh
  - source travis-utils/env-setup.sh
  - export TARGET_PERL=https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/perl-5.30.3.tar.xz
  - source travis-utils/get_perl.sh
  - tar -xf /tmp/perl.tar.xz --strip-components 1 -C ${S}
script:
  - source travis-utils/emsg.sh
  - source travis-utils/env-setup.sh
  - if [ -z "$VANILLA" ]; then source travis-utils/clean-patches.sh; fi
  - if [ -z "$VANILLA" ]; then source travis-utils/patchlevel-hack.sh; fi
  - if [ -z "$VANILLA" ]; then source travis-utils/setup-patchlist.sh; fi
  - if [ -z "$VANILLA" ]; then source travis-utils/apply-patches.sh; fi
  - if [ -z "$VANILLA" ]; then source travis-utils/gen_patchlevel_ng.sh; fi
  - if [ -z "$VANILLA" ]; then source travis-utils/update-manifest.sh; fi
  - source travis-utils/compile-perl.sh
