matrix:
  fast_finish: true
  include:
      - env: CLANG_VERSION=3.4 TARGET_PERL=https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.24.0.tar.bz2
        compiler: clang34
        addons: &clang34
          apt:
            sources:
              - ubuntu-toolchain-r-test
      - env: GCC_VERSION=5 TARGET_PERL=https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.24.0.tar.bz2
        compiler: gcc-5
        addons: &gcc5
          apt:
            packages:
              - g++-5
              - gcc-5
            sources:
              - ubuntu-toolchain-r-test
      - env: GCC_VERSION=6 TARGET_PERL=https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.24.0.tar.bz2
        compiler: gcc-6
        addons: &gcc6
          apt:
            packages:
              - g++-6
              - gcc-6
            sources:
              - ubuntu-toolchain-r-test
      - env: TARGET_PERL=https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.24.0.tar.bz2
        compiler: gcc
      - env: myconf="-Dusethreads" TARGET_PERL=https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.24.0.tar.bz2
        compiler: gcc
      - env: myconf="-DDEBUGGING" TARGET_PERL=https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.24.0.tar.bz2
        compiler: gcc
      - env: CLANG_VERSION=3.8 TARGET_PERL=https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.24.0.tar.bz2
        compiler: clang38
        addons:
          apt:
            packages:
              - clang-3.8
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-precise-3.8
language: c
before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [ "$CLANG_VERSION" == "3.4" ]; then export CXX="/usr/local/clang-3.4/bin/clang++" CC="/usr/local/clang-3.4/bin/clang"; fi
install:
  - source travis-utils/emsg.sh
  - source travis-utils/env-setup.sh
  - source travis-utils/get_perl.sh
  - tar -xf /tmp/perl.tar.bz2 --strip-components 1 -C ${S}
script:
  - source travis-utils/emsg.sh
  - source travis-utils/env-setup.sh
  - source travis-utils/patch-perl.sh
  - source travis-utils/compile-perl.sh
